export const studentData = [
  {
    name: "Rahul Sharma",
    phone: "9876543210",
    email: "rahul@example.com",
    address: "Dehradun, Uttarakhand",
    course: "Web Development",
    education: "B.Tech",
    message: "Interested in frontend development",
    date: "2025-01-12",
    // status:
  },
  {
    name: "Anjali Verma",
    phone: "9123456780",
    email: "anjali@example.com",
    address: "Haridwar, Uttarakhand",
    course: "Graphic Design",
    education: "BA",
    message: "Looking for creative courses",
    date: "2025-01-10",
  },
  {
    name: "Rohit Singh",
    phone: "9988776655",
    email: "rohit@example.com",
    address: "Haldwani",
    course: "Digital Marketing",
    education: "MBA",
    message: "Want to learn SEO",
    date: "2025-01-08",
  },
  {
    name: "Priya Chauhan",
    phone: "9090909090",
    email: "priya@example.com",
    address: "Rishikesh",
    course: "Python Programming",
    education: "B.Sc",
    message: "Interested in data science",
    date: "2025-01-05",
  },
  {
    name: "Deepak Rawat",
    phone: "9800001122",
    email: "deepak@example.com",
    address: "Roorkee",
    course: "Web Development",
    education: "Diploma",
    message: "Wants full-stack course",
    date: "2025-01-03",
  },
  {
    name: "Meena Joshi",
    phone: "9700004433",
    email: "meena@example.com",
    address: "Pauri Garhwal",
    course: "Tally ERP",
    education: "B.Com",
    message: "Wants accounting course",
    date: "2025-01-01",
  },
  {
    name: "Amit Kumar",
    phone: "9301234567",
    email: "amit@example.com",
    address: "Almora",
    course: "Java Programming",
    education: "BCA",
    message: "Looking to upgrade skills",
    date: "2024-12-28",
  },
  {
    name: "Simran Kaur",
    phone: "9991122334",
    email: "simran@example.com",
    address: "Nainital",
    course: "UI/UX Design",
    education: "B.Des",
    message: "Interested in designing",
    date: "2024-12-20",
  },
  {
    name: "Vijay Pal",
    phone: "9870007654",
    email: "vijay@example.com",
    address: "Kotdwar",
    course: "English Speaking",
    education: "12th",
    message: "Want to improve English",
    date: "2024-12-15",
  },
  {
    name: "Sneha Kapoor",
    phone: "9988002211",
    email: "sneha@example.com",
    address: "Mussoorie",
    course: "Computer Basics",
    education: "10th",
    message: "Beginner in computers",
    date: "2024-12-10",
  },
];
